### ISSUE TITLE
Bullet com o logo do Raíz

### ISSUE THREAD

**Issue by josircg** [josircg/raizcidadanista#30]
Temos que melhorar a visualização dos bullets do site:

CSS

```css
.bullets{
     padding:6px 0 6px 40px;
     background:url(http://www.raiz.org.br/media/uploads/2015_imagens_menu_lateral/RAIZ_-001.jpg) no-repeat center left;}

.bullets img{display:none;}
```

E depois incluir nos artigos que tem bullets:

```html
<p class="bullets">
      <img alt="" src="/media/uploads/raiz_logos_imagens/raiz_-001.jpg" style="width: 30px; height: 30px; margin-right: 10px; margin-left: 10px; float: left;" />
      <strong><a href="/media/uploads/documentos_da_raiz/carta-cidadanista-imp.pdf" target="_blank">CARTA CIDADANISTA</a> para impress&atilde;o em PB</strong>
</p>

Sem img:

<p class="bullets">
      <strong><a href="/media/uploads/documentos_da_raiz/carta-cidadanista-imp.pdf" target="_blank">CARTA CIDADANISTA</a> para impress&atilde;o em PB</strong>
</p>
```
